name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.3"

      - name: Install Forester
        run: |
          git clone https://git.sr.ht/~jonsterling/ocaml-forester
          cd ocaml-forester
          git checkout forester-5.0-dev
          opam pin add -y .

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-medium
            standalone
            mlmodern
            amsfonts
            amsmath
            zx-calculus
            tikz-cd
            l3packages
            dvisvgm
            pgf
            etoolbox
            mathtools
            stmaryrd
            newtx
            newpx
            xstring
            fontaxes
            kastrup
            spath3
            xpatch
            forest
            libertine

      - name: Check `latex` version
        run: latex --version

      - name: Build with Forester
        run: |
          opam exec -- forester build forest.toml

      - name: Setup upterm session
        if: failure()
        uses: lhotari/action-upterm@v1

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./output/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
